[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesopt"
version = "0.0.1"
authors = [{name="Brenden Pelkie", email="bgpelkie@gmail.com"}]
description = "Bayesian Optimization for Design of Experiments course"
requires-python = ">3.7"
